#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, it displays "Best School" and then "Hi" on a new line.

x=0

while [ $x -lt 10 ]
do
    if [ $x -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    ((x++))
done
